services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app_network
    restart: always

  redis:
    image: redis:alpine
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
